// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogDocumentDataSlicesSlice = BannerSlice | BlogPostSlice;

/**
 * Content for Blog documents
 */
interface BlogDocumentData {
  /**
   * Slice Zone field in *Blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Canonical Link field in *Blog*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.canonicalLink
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  canonicalLink: prismic.LinkField;

  /**
   * OG Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.og_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  og_title: prismic.KeyTextField;

  /**
   * OG Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.og_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  og_description: prismic.KeyTextField;

  /**
   * OG Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.og_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;
}

/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, "blog", Lang>;

type BlogPostDocumentDataSlicesSlice =
  | BrandsSlice
  | ImageContentWithColumnSlice;

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogPost.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Short Description field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogPost.shortDesc
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  shortDesc: prismic.RichTextField;

  /**
   * Author field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogPost.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Publish Date field in *Blog Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blogPost.publishDate
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publishDate: prismic.DateField;

  /**
   * Featured Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogPost.featuredImg
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featuredImg: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blogPost.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blogPost.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blogPost.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogPost.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Canonical Link field in *Blog Post*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: blogPost.canonicalLink
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  canonicalLink: prismic.LinkField;

  /**
   * OG Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogPost.og_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  og_title: prismic.KeyTextField;

  /**
   * OG Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogPost.og_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  og_description: prismic.KeyTextField;

  /**
   * OG Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogPost.og_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blogPost`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blogPost",
    Lang
  >;

/**
 * Item in *Footer → Social Data*
 */
export interface FooterDocumentDataSocialDataItem {
  /**
   * Social Image field in *Footer → Social Data*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.socialData[].socialmage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  socialmage: prismic.ImageField<never>;

  /**
   * Social Link field in *Footer → Social Data*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.socialData[].socialLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  socialLink: prismic.LinkField;
}

type FooterDocumentDataSlicesSlice = LinkSectionSlice;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Logo Image field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logoImage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logoImage: prismic.ImageField<never>;

  /**
   * Logo Link field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logoLink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  logoLink: prismic.LinkField;

  /**
   * Title field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Address field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  address: prismic.RichTextField;

  /**
   * Social Data field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.socialData[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  socialData: prismic.GroupField<Simplify<FooterDocumentDataSocialDataItem>>;

  /**
   * Copyright Text field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.copyrightText
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyrightText: prismic.KeyTextField;

  /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | BannerSlice
  | ProjectSlice
  | StatisticsSlice
  | ClientsSlice
  | BrandsSlice
  | FaqSlice
  | ContactSlice
  | HeroSectionSlice
  | ImageContentWithColumnSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Canonical Link field in *Homepage*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.canonicalLink
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  canonicalLink: prismic.LinkField;

  /**
   * OG Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.og_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  og_title: prismic.KeyTextField;

  /**
   * OG Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.og_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  og_description: prismic.KeyTextField;

  /**
   * OG Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.og_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type NavbarDocumentDataSlicesSlice = MenusSlice;

/**
 * Content for Navbar documents
 */
interface NavbarDocumentData {
  /**
   * Logo Image field in *Navbar*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.logoImg
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logoImg: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Navbar*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavbarDocumentDataSlicesSlice>;
}

/**
 * Navbar document from Prismic
 *
 * - **API ID**: `navbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavbarDocumentData>,
    "navbar",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | ImageContentWithColumnSlice
  | WhyusSlice
  | BannerSlice
  | CardsSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *TopNavbar → Navbar Data*
 */
export interface TopNavbarDocumentDataNavDataItem {
  /**
   * Label field in *TopNavbar → Navbar Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: topNavbar.navData[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *TopNavbar → Navbar Data*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: topNavbar.navData[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for TopNavbar documents
 */
interface TopNavbarDocumentData {
  /**
   * Navbar Data field in *TopNavbar*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: topNavbar.navData[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navData: prismic.GroupField<Simplify<TopNavbarDocumentDataNavDataItem>>;
}

/**
 * TopNavbar document from Prismic
 *
 * - **API ID**: `topNavbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TopNavbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TopNavbarDocumentData>,
    "topNavbar",
    Lang
  >;

export type AllDocumentTypes =
  | BlogDocument
  | BlogPostDocument
  | FooterDocument
  | HomepageDocument
  | NavbarDocument
  | PageDocument
  | TopNavbarDocument;

/**
 * Item in *Banner → Default → Primary → Buttons*
 */
export interface BannerSliceDefaultPrimaryButtonsItem {
  /**
   * Button Label field in *Banner → Default → Primary → Buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.buttons[].buttonLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonLabel: prismic.KeyTextField;

  /**
   * Button Link field in *Banner → Default → Primary → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.buttons[].buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;
}

/**
 * Item in *Banner → Short Banner → Primary → Buttons*
 */
export interface BannerSliceShortBannerPrimaryButtonsItem {
  /**
   * Button Label field in *Banner → Short Banner → Primary → Buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.shortBanner.primary.buttons[].buttonLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonLabel: prismic.KeyTextField;

  /**
   * Button Link field in *Banner → Short Banner → Primary → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.shortBanner.primary.buttons[].buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;
}

/**
 * Primary content in *Banner → Default → Primary*
 */
export interface BannerSliceDefaultPrimary {
  /**
   * Title field in *Banner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Sub Title field in *Banner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.subTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subTitle: prismic.KeyTextField;

  /**
   * Buttons field in *Banner → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  buttons: prismic.GroupField<Simplify<BannerSliceDefaultPrimaryButtonsItem>>;

  /**
   * Banner Image field in *Banner → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.bannerImg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bannerImg: prismic.ImageField<never>;
}

/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Banner → Short Banner → Primary*
 */
export interface BannerSliceShortBannerPrimary {
  /**
   * Title field in *Banner → Short Banner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.shortBanner.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Title2 field in *Banner → Short Banner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.shortBanner.primary.title2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title2: prismic.KeyTextField;

  /**
   * Sub Title field in *Banner → Short Banner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.shortBanner.primary.subTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subTitle: prismic.KeyTextField;

  /**
   * Buttons field in *Banner → Short Banner → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.shortBanner.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  buttons: prismic.GroupField<
    Simplify<BannerSliceShortBannerPrimaryButtonsItem>
  >;

  /**
   * Banner Image field in *Banner → Short Banner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.shortBanner.primary.bannerImg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bannerImg: prismic.ImageField<never>;
}

/**
 * Short Banner variation for Banner Slice
 *
 * - **API ID**: `shortBanner`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceShortBanner = prismic.SharedSliceVariation<
  "shortBanner",
  Simplify<BannerSliceShortBannerPrimary>,
  never
>;

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation = BannerSliceDefault | BannerSliceShortBanner;

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSlice = prismic.SharedSlice<"banner", BannerSliceVariation>;

/**
 * Primary content in *BlogPost → Default → Primary*
 */
export interface BlogPostSliceDefaultPrimary {
  /**
   * Blog Image field in *BlogPost → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.default.primary.blogImg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  blogImg: prismic.ImageField<never>;

  /**
   * Blog Title field in *BlogPost → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.default.primary.blogTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  blogTitle: prismic.KeyTextField;

  /**
   * Blog Description field in *BlogPost → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.default.primary.blogDesc
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  blogDesc: prismic.RichTextField;
}

/**
 * Default variation for BlogPost Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogPostSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogPost*
 */
type BlogPostSliceVariation = BlogPostSliceDefault;

/**
 * BlogPost Shared Slice
 *
 * - **API ID**: `blog_post`
 * - **Description**: BlogPost
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostSlice = prismic.SharedSlice<
  "blog_post",
  BlogPostSliceVariation
>;

/**
 * Item in *Brands → Default → Primary → Brand Images*
 */
export interface BrandsSliceDefaultPrimaryBrandImagesItem {
  /**
   * Image field in *Brands → Default → Primary → Brand Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: brands.default.primary.brandImages[].Img
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  Img: prismic.ImageField<never>;
}

/**
 * Primary content in *Brands → Default → Primary*
 */
export interface BrandsSliceDefaultPrimary {
  /**
   * Title1 field in *Brands → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: brands.default.primary.title1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title1: prismic.KeyTextField;

  /**
   * Title2 field in *Brands → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: brands.default.primary.title2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title2: prismic.KeyTextField;

  /**
   * Description field in *Brands → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: brands.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Brand Images field in *Brands → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: brands.default.primary.brandImages[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  brandImages: prismic.GroupField<
    Simplify<BrandsSliceDefaultPrimaryBrandImagesItem>
  >;
}

/**
 * Default variation for Brands Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BrandsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BrandsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Brands*
 */
type BrandsSliceVariation = BrandsSliceDefault;

/**
 * Brands Shared Slice
 *
 * - **API ID**: `brands`
 * - **Description**: Brands
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BrandsSlice = prismic.SharedSlice<"brands", BrandsSliceVariation>;

/**
 * Item in *Cards → Default → Primary → Card Data*
 */
export interface CardsSliceDefaultPrimaryCardDataItem {
  /**
   * Card Image field in *Cards → Default → Primary → Card Data*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.cardData[].cardImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cardImage: prismic.ImageField<never>;

  /**
   * card Video field in *Cards → Default → Primary → Card Data*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.cardData[].cardVideo
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  cardVideo: prismic.EmbedField;

  /**
   * Card Title field in *Cards → Default → Primary → Card Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.cardData[].cardTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardTitle: prismic.KeyTextField;

  /**
   * Card Description field in *Cards → Default → Primary → Card Data*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.cardData[].cardDesc
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cardDesc: prismic.RichTextField;

  /**
   * More Description field in *Cards → Default → Primary → Card Data*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.cardData[].moreDesc
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  moreDesc: prismic.RichTextField;
}

/**
 * Item in *Cards → Cards without Text → Primary → Card Data*
 */
export interface CardsSliceCardsWithoutTextPrimaryCardDataItem {
  /**
   * Card Image field in *Cards → Cards without Text → Primary → Card Data*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.cardsWithoutText.primary.cardData[].cardImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cardImage: prismic.ImageField<never>;

  /**
   * Card Title field in *Cards → Cards without Text → Primary → Card Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.cardsWithoutText.primary.cardData[].cardTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardTitle: prismic.KeyTextField;

  /**
   * Card Description field in *Cards → Cards without Text → Primary → Card Data*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.cardsWithoutText.primary.cardData[].cardDesc
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cardDesc: prismic.RichTextField;

  /**
   * More Description field in *Cards → Cards without Text → Primary → Card Data*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.cardsWithoutText.primary.cardData[].moreDesc
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  moreDesc: prismic.RichTextField;

  /**
   * imgWithoutText field in *Cards → Cards without Text → Primary → Card Data*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.cardsWithoutText.primary.cardData[].imgwithouttext
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imgwithouttext: prismic.ImageField<never>;
}

/**
 * Primary content in *Cards → Default → Primary*
 */
export interface CardsSliceDefaultPrimary {
  /**
   * Title1 field in *Cards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.title1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title1: prismic.KeyTextField;

  /**
   * Title2 field in *Cards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.title2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title2: prismic.KeyTextField;

  /**
   * Card Data field in *Cards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.cardData[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cardData: prismic.GroupField<Simplify<CardsSliceDefaultPrimaryCardDataItem>>;
}

/**
 * Default variation for Cards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardsSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Cards → Cards without Text → Primary*
 */
export interface CardsSliceCardsWithoutTextPrimary {
  /**
   * Title1 field in *Cards → Cards without Text → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.cardsWithoutText.primary.title1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title1: prismic.KeyTextField;

  /**
   * Title2 field in *Cards → Cards without Text → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.cardsWithoutText.primary.title2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title2: prismic.KeyTextField;

  /**
   * Card Data field in *Cards → Cards without Text → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.cardsWithoutText.primary.cardData[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cardData: prismic.GroupField<
    Simplify<CardsSliceCardsWithoutTextPrimaryCardDataItem>
  >;
}

/**
 * Cards without Text variation for Cards Slice
 *
 * - **API ID**: `cardsWithoutText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSliceCardsWithoutText = prismic.SharedSliceVariation<
  "cardsWithoutText",
  Simplify<CardsSliceCardsWithoutTextPrimary>,
  never
>;

/**
 * Slice variation for *Cards*
 */
type CardsSliceVariation = CardsSliceDefault | CardsSliceCardsWithoutText;

/**
 * Cards Shared Slice
 *
 * - **API ID**: `cards`
 * - **Description**: Cards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSlice = prismic.SharedSlice<"cards", CardsSliceVariation>;

/**
 * Item in *Clients → Default → Primary → Client Data*
 */
export interface ClientsSliceDefaultPrimaryClientDataItem {
  /**
   * Image field in *Clients → Default → Primary → Client Data*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.default.primary.clientData[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *Clients → Default → Primary → Client Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.default.primary.clientData[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Position field in *Clients → Default → Primary → Client Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.default.primary.clientData[].position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;

  /**
   * Description field in *Clients → Default → Primary → Client Data*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.default.primary.clientData[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Clients → Default → Primary*
 */
export interface ClientsSliceDefaultPrimary {
  /**
   * Title1 field in *Clients → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.default.primary.title1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title1: prismic.KeyTextField;

  /**
   * Title2 field in *Clients → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.default.primary.title2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title2: prismic.KeyTextField;

  /**
   * Title3 field in *Clients → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.default.primary.title3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title3: prismic.KeyTextField;

  /**
   * Client Data field in *Clients → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.default.primary.clientData[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  clientData: prismic.GroupField<
    Simplify<ClientsSliceDefaultPrimaryClientDataItem>
  >;
}

/**
 * Default variation for Clients Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClientsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ClientsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Clients*
 */
type ClientsSliceVariation = ClientsSliceDefault;

/**
 * Clients Shared Slice
 *
 * - **API ID**: `clients`
 * - **Description**: Clients
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClientsSlice = prismic.SharedSlice<
  "clients",
  ClientsSliceVariation
>;

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * Image field in *Contact → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title1 field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.title1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title1: prismic.KeyTextField;

  /**
   * Title2 field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.title2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title2: prismic.KeyTextField;

  /**
   * Description field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Item in *Faq → Default → Primary → Faqs*
 */
export interface FaqSliceDefaultPrimaryFaqsItem {
  /**
   * Heading field in *Faq → Default → Primary → Faqs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.faqs[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *Faq → Default → Primary → Faqs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.faqs[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Faq → Default → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * Title1 field in *Faq → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.title1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title1: prismic.KeyTextField;

  /**
   * Title2 field in *Faq → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.title2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title2: prismic.KeyTextField;

  /**
   * Description field in *Faq → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Faqs field in *Faq → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.faqs[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  faqs: prismic.GroupField<Simplify<FaqSliceDefaultPrimaryFaqsItem>>;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * BgImage field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.bgImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bgImage: prismic.ImageField<never>;

  /**
   * Heading field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * SubHeading field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.subHeading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subHeading: prismic.KeyTextField;

  /**
   * ButtonName field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.BtnName
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  BtnName: prismic.KeyTextField;

  /**
   * BtnLink field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.BtnLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  BtnLink: prismic.LinkField;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Primary content in *ImageContentWithColumn → Default → Primary*
 */
export interface ImageContentWithColumnSliceDefaultPrimary {
  /**
   * Image field in *ImageContentWithColumn → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_content_with_column.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title1 field in *ImageContentWithColumn → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_content_with_column.default.primary.title1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title1: prismic.KeyTextField;

  /**
   * Title2 field in *ImageContentWithColumn → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_content_with_column.default.primary.title2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title2: prismic.KeyTextField;

  /**
   * Description1 field in *ImageContentWithColumn → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_content_with_column.default.primary.description1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description1: prismic.RichTextField;

  /**
   * Description2 field in *ImageContentWithColumn → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_content_with_column.default.primary.description2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description2: prismic.RichTextField;
}

/**
 * Default variation for ImageContentWithColumn Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageContentWithColumnSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageContentWithColumnSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ImageContentWithColumn → Image at Right Side → Primary*
 */
export interface ImageContentWithColumnSliceImageAtRightSidePrimary {
  /**
   * Image field in *ImageContentWithColumn → Image at Right Side → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_content_with_column.imageAtRightSide.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title1 field in *ImageContentWithColumn → Image at Right Side → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_content_with_column.imageAtRightSide.primary.title1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title1: prismic.KeyTextField;

  /**
   * Title2 field in *ImageContentWithColumn → Image at Right Side → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_content_with_column.imageAtRightSide.primary.title2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title2: prismic.KeyTextField;

  /**
   * Description1 field in *ImageContentWithColumn → Image at Right Side → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_content_with_column.imageAtRightSide.primary.description1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description1: prismic.RichTextField;

  /**
   * Description2 field in *ImageContentWithColumn → Image at Right Side → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_content_with_column.imageAtRightSide.primary.description2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description2: prismic.RichTextField;
}

/**
 * Image at Right Side variation for ImageContentWithColumn Slice
 *
 * - **API ID**: `imageAtRightSide`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageContentWithColumnSliceImageAtRightSide =
  prismic.SharedSliceVariation<
    "imageAtRightSide",
    Simplify<ImageContentWithColumnSliceImageAtRightSidePrimary>,
    never
  >;

/**
 * Slice variation for *ImageContentWithColumn*
 */
type ImageContentWithColumnSliceVariation =
  | ImageContentWithColumnSliceDefault
  | ImageContentWithColumnSliceImageAtRightSide;

/**
 * ImageContentWithColumn Shared Slice
 *
 * - **API ID**: `image_content_with_column`
 * - **Description**: ImageContentWithColumn
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageContentWithColumnSlice = prismic.SharedSlice<
  "image_content_with_column",
  ImageContentWithColumnSliceVariation
>;

/**
 * Item in *LinkSection → Default → Primary → Links*
 */
export interface LinkSectionSliceDefaultPrimaryLinksItem {
  /**
   * Link Label field in *LinkSection → Default → Primary → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_section.default.primary.links[].linkLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linkLabel: prismic.KeyTextField;

  /**
   * Link field in *LinkSection → Default → Primary → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: link_section.default.primary.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *LinkSection → Default → Primary*
 */
export interface LinkSectionSliceDefaultPrimary {
  /**
   * Heading field in *LinkSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Links field in *LinkSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: link_section.default.primary.links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<LinkSectionSliceDefaultPrimaryLinksItem>>;
}

/**
 * Default variation for LinkSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LinkSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LinkSection*
 */
type LinkSectionSliceVariation = LinkSectionSliceDefault;

/**
 * LinkSection Shared Slice
 *
 * - **API ID**: `link_section`
 * - **Description**: LinkSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkSectionSlice = prismic.SharedSlice<
  "link_section",
  LinkSectionSliceVariation
>;

/**
 * Item in *Menus → Default → Primary → ChildMenus*
 */
export interface MenusSliceDefaultPrimaryChildmenusItem {
  /**
   * MenuLabel field in *Menus → Default → Primary → ChildMenus*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menus.default.primary.childmenus[].menulabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  menulabel: prismic.KeyTextField;

  /**
   * MenuLink field in *Menus → Default → Primary → ChildMenus*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menus.default.primary.childmenus[].menulink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  menulink: prismic.LinkField;
}

/**
 * Primary content in *Menus → Default → Primary*
 */
export interface MenusSliceDefaultPrimary {
  /**
   * MenuLabel field in *Menus → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menus.default.primary.menulabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  menulabel: prismic.KeyTextField;

  /**
   * MenuLink field in *Menus → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menus.default.primary.menulink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  menulink: prismic.LinkField;

  /**
   * ChildMenus field in *Menus → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menus.default.primary.childmenus[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  childmenus: prismic.GroupField<
    Simplify<MenusSliceDefaultPrimaryChildmenusItem>
  >;
}

/**
 * Default variation for Menus Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenusSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MenusSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Menus*
 */
type MenusSliceVariation = MenusSliceDefault;

/**
 * Menus Shared Slice
 *
 * - **API ID**: `menus`
 * - **Description**: Menus
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenusSlice = prismic.SharedSlice<"menus", MenusSliceVariation>;

/**
 * Item in *Project → Default → Primary → Card Data*
 */
export interface ProjectSliceDefaultPrimaryCardDataItem {
  /**
   * CardImage field in *Project → Default → Primary → Card Data*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.cardData[].cardImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cardImage: prismic.ImageField<never>;

  /**
   * Heading field in *Project → Default → Primary → Card Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.cardData[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *Project → Default → Primary → Card Data*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.cardData[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Client Label field in *Project → Default → Primary → Card Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.cardData[].clientLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  clientLabel: prismic.KeyTextField;

  /**
   * Client Name field in *Project → Default → Primary → Card Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.cardData[].clientName
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  clientName: prismic.KeyTextField;
}

/**
 * Item in *Project → Default → Primary → Icon Images*
 */
export interface ProjectSliceDefaultPrimaryIconImagesItem {
  /**
   * Title field in *Project → Default → Primary → Icon Images*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.iconImages[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Icon Image field in *Project → Default → Primary → Icon Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.iconImages[].iconImg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  iconImg: prismic.ImageField<never>;
}

/**
 * Primary content in *Project → Default → Primary*
 */
export interface ProjectSliceDefaultPrimary {
  /**
   * Title1 field in *Project → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.title1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title1: prismic.KeyTextField;

  /**
   * Title2 field in *Project → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.title2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title2: prismic.KeyTextField;

  /**
   * Description field in *Project → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Card Data field in *Project → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.cardData[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cardData: prismic.GroupField<
    Simplify<ProjectSliceDefaultPrimaryCardDataItem>
  >;

  /**
   * Icon Images field in *Project → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.iconImages[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  iconImages: prismic.GroupField<
    Simplify<ProjectSliceDefaultPrimaryIconImagesItem>
  >;
}

/**
 * Default variation for Project Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Project*
 */
type ProjectSliceVariation = ProjectSliceDefault;

/**
 * Project Shared Slice
 *
 * - **API ID**: `project`
 * - **Description**: Project
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectSlice = prismic.SharedSlice<
  "project",
  ProjectSliceVariation
>;

/**
 * Item in *Statistics → Default → Primary → Statistics*
 */
export interface StatisticsSliceDefaultPrimaryStatisticsItem {
  /**
   * Label field in *Statistics → Default → Primary → Statistics*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: statistics.default.primary.statistics[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Count field in *Statistics → Default → Primary → Statistics*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: statistics.default.primary.statistics[].count
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  count: prismic.KeyTextField;
}

/**
 * Primary content in *Statistics → Default → Primary*
 */
export interface StatisticsSliceDefaultPrimary {
  /**
   * Statistics field in *Statistics → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: statistics.default.primary.statistics[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  statistics: prismic.GroupField<
    Simplify<StatisticsSliceDefaultPrimaryStatisticsItem>
  >;
}

/**
 * Default variation for Statistics Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatisticsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StatisticsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Statistics*
 */
type StatisticsSliceVariation = StatisticsSliceDefault;

/**
 * Statistics Shared Slice
 *
 * - **API ID**: `statistics`
 * - **Description**: Statistics
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatisticsSlice = prismic.SharedSlice<
  "statistics",
  StatisticsSliceVariation
>;

/**
 * Item in *Whyus → Default → Primary → Icons Data*
 */
export interface WhyusSliceDefaultPrimaryIconsDataItem {
  /**
   * Icon Image field in *Whyus → Default → Primary → Icons Data*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: whyus.default.primary.iconsData[].iconImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  iconImage: prismic.ImageField<never>;

  /**
   * Icon Title field in *Whyus → Default → Primary → Icons Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whyus.default.primary.iconsData[].iconTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  iconTitle: prismic.KeyTextField;
}

/**
 * Primary content in *Whyus → Default → Primary*
 */
export interface WhyusSliceDefaultPrimary {
  /**
   * Title1 field in *Whyus → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whyus.default.primary.title1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title1: prismic.KeyTextField;

  /**
   * Title2 field in *Whyus → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whyus.default.primary.title2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title2: prismic.KeyTextField;

  /**
   * Icons Data field in *Whyus → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: whyus.default.primary.iconsData[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  iconsData: prismic.GroupField<
    Simplify<WhyusSliceDefaultPrimaryIconsDataItem>
  >;
}

/**
 * Default variation for Whyus Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhyusSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhyusSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Whyus*
 */
type WhyusSliceVariation = WhyusSliceDefault;

/**
 * Whyus Shared Slice
 *
 * - **API ID**: `whyus`
 * - **Description**: Whyus
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhyusSlice = prismic.SharedSlice<"whyus", WhyusSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSocialDataItem,
      FooterDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      NavbarDocument,
      NavbarDocumentData,
      NavbarDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      TopNavbarDocument,
      TopNavbarDocumentData,
      TopNavbarDocumentDataNavDataItem,
      AllDocumentTypes,
      BannerSlice,
      BannerSliceDefaultPrimaryButtonsItem,
      BannerSliceDefaultPrimary,
      BannerSliceShortBannerPrimaryButtonsItem,
      BannerSliceShortBannerPrimary,
      BannerSliceVariation,
      BannerSliceDefault,
      BannerSliceShortBanner,
      BlogPostSlice,
      BlogPostSliceDefaultPrimary,
      BlogPostSliceVariation,
      BlogPostSliceDefault,
      BrandsSlice,
      BrandsSliceDefaultPrimaryBrandImagesItem,
      BrandsSliceDefaultPrimary,
      BrandsSliceVariation,
      BrandsSliceDefault,
      CardsSlice,
      CardsSliceDefaultPrimaryCardDataItem,
      CardsSliceDefaultPrimary,
      CardsSliceCardsWithoutTextPrimaryCardDataItem,
      CardsSliceCardsWithoutTextPrimary,
      CardsSliceVariation,
      CardsSliceDefault,
      CardsSliceCardsWithoutText,
      ClientsSlice,
      ClientsSliceDefaultPrimaryClientDataItem,
      ClientsSliceDefaultPrimary,
      ClientsSliceVariation,
      ClientsSliceDefault,
      ContactSlice,
      ContactSliceDefaultPrimary,
      ContactSliceVariation,
      ContactSliceDefault,
      FaqSlice,
      FaqSliceDefaultPrimaryFaqsItem,
      FaqSliceDefaultPrimary,
      FaqSliceVariation,
      FaqSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      ImageContentWithColumnSlice,
      ImageContentWithColumnSliceDefaultPrimary,
      ImageContentWithColumnSliceImageAtRightSidePrimary,
      ImageContentWithColumnSliceVariation,
      ImageContentWithColumnSliceDefault,
      ImageContentWithColumnSliceImageAtRightSide,
      LinkSectionSlice,
      LinkSectionSliceDefaultPrimaryLinksItem,
      LinkSectionSliceDefaultPrimary,
      LinkSectionSliceVariation,
      LinkSectionSliceDefault,
      MenusSlice,
      MenusSliceDefaultPrimaryChildmenusItem,
      MenusSliceDefaultPrimary,
      MenusSliceVariation,
      MenusSliceDefault,
      ProjectSlice,
      ProjectSliceDefaultPrimaryCardDataItem,
      ProjectSliceDefaultPrimaryIconImagesItem,
      ProjectSliceDefaultPrimary,
      ProjectSliceVariation,
      ProjectSliceDefault,
      StatisticsSlice,
      StatisticsSliceDefaultPrimaryStatisticsItem,
      StatisticsSliceDefaultPrimary,
      StatisticsSliceVariation,
      StatisticsSliceDefault,
      WhyusSlice,
      WhyusSliceDefaultPrimaryIconsDataItem,
      WhyusSliceDefaultPrimary,
      WhyusSliceVariation,
      WhyusSliceDefault,
    };
  }
}
