// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  brands: dynamic(() => import("./Brands")),
  clients: dynamic(() => import("./Clients")),
  contact: dynamic(() => import("./Contact")),
  faq: dynamic(() => import("./Faq")),
  hero_section: dynamic(() => import("./HeroSection")),
  image_content_with_column: dynamic(() => import("./ImageContentWithColumn")),
};
